//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountantReports
    {
        public int reportID { get; set; }
        public decimal totalCost { get; set; }
        public int insuranceCompanyID { get; set; }
        public int userID { get; set; }
        public System.DateTime periodStart { get; set; }
        public System.DateTime periodEnd { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual insuranceCompany insuranceCompany { get; set; }
        public virtual users users { get; set; }
    }
}
