//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyzerWorks
    {
        public int analyzerWorkID { get; set; }
        public int orderServiceID { get; set; }
        public int analyzerID { get; set; }
        public int userID { get; set; }
        public System.DateTime performedAt { get; set; }
    
        public virtual analyzers analyzers { get; set; }
        public virtual users users { get; set; }
        public virtual orderServices orderServices { get; set; }
    }
}
