//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orderServices()
        {
            this.analyzerWorks = new HashSet<analyzerWorks>();
        }
    
        public int orderServiceID { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> serviceCodeID { get; set; }
        public Nullable<int> orderServiceStatusID { get; set; }
        public string barcode { get; set; }
        public string result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<analyzerWorks> analyzerWorks { get; set; }
        public virtual orders orders { get; set; }
        public virtual orderServiceStatuses orderServiceStatuses { get; set; }
        public virtual services services { get; set; }
    }
}
