//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public services()
        {
            this.orderServices = new HashSet<orderServices>();
        }
    
        public int serviceCodeID { get; set; }
        public string serviceName { get; set; }
        public Nullable<double> servicePrice { get; set; }
        public Nullable<int> executionTime { get; set; }
        public string normalRangeStart { get; set; }
        public string normalRangeEnd { get; set; }
        public Nullable<int> analyzerID { get; set; }
    
        public virtual analyzers analyzers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderServices> orderServices { get; set; }
    }
}
