//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessionHistories
    {
        public int sessionID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> loginTime { get; set; }
        public Nullable<System.DateTime> logoutTime { get; set; }
        public Nullable<bool> wasSuccessful { get; set; }
        public string ip { get; set; }
    
        public virtual users users { get; set; }
    }
}
