//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.accountantReports = new HashSet<accountantReports>();
            this.analyzerWorks = new HashSet<analyzerWorks>();
            this.orders = new HashSet<orders>();
            this.sessionHistories = new HashSet<sessionHistories>();
        }
    
        public int userID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string fullName { get; set; }
        public Nullable<int> roleID { get; set; }
        public string img { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string passportNumber { get; set; }
        public string passportSeries { get; set; }
        public string policyNumber { get; set; }
        public Nullable<int> policyTypeID { get; set; }
        public Nullable<int> insuranceCompanyID { get; set; }
        public Nullable<int> documentTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accountantReports> accountantReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<analyzerWorks> analyzerWorks { get; set; }
        public virtual documentTypes documentTypes { get; set; }
        public virtual insuranceCompany insuranceCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        public virtual policyTypes policyTypes { get; set; }
        public virtual roles roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sessionHistories> sessionHistories { get; set; }
    }
}
